### ISSUE TITLE
Implement websocket client.

### ISSUE THREAD

**Issue by creationix** [magic-script/magic-script-polyfills#6]
We've already got websocket code in the weblit dependency.  It should be fairly simple to add browser style websocket client APIs to compliment fetch.

**Comment by framinlab** [comment]
Any idea on ETA for websocket with TLS/SSL support in MagicScript? Thanks!

**Comment by creationix** [comment]
I'm working on this today.  Hopefully it will be done later today, if not it will be done tomorrow.

**Comment by creationix** [comment]
Implemented in: 35684eeb2e45c4b133419135f9193343ce3af291
Published in: magic-script-polyfills@2.4.0

See test for examples of usage: https://github.com/magic-script/magic-script-polyfills/blob/master/tests/test-websocket.js
